import { Elysia } from 'elysia';

function buildDocsHtml(): string {
  return [
    '<!DOCTYPE html>',
    '<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">',
    '<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Inter:wght@300..700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">',
    '<title>SB0 Pay — Integration Guide</title>',
    '<style>',
    ':root{--bg:#091a0f;--card:#0f1f14;--border:#1a3324;--text:#f0faf5;--muted:#8aac9a;--accent:#13b981;--accent-light:#34d399;--green:#22c55e;--red:#ef4444;--orange:#f59e0b;--code:#34d399}',
    '*{margin:0;padding:0;box-sizing:border-box}',
    'body{font-family:"Inter",-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:var(--bg);color:var(--text);line-height:1.7;background-image:radial-gradient(ellipse at top,hsl(158 84% 45%/.12),transparent 60%);background-attachment:fixed}',
    '.wrap{max-width:900px;margin:0 auto;padding:2rem 1.5rem 4rem}',
    'h1{font-family:"Instrument Serif",Georgia,serif;font-size:2.5rem;font-weight:800;background:linear-gradient(135deg,var(--accent),#34d399);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:.25rem}',
    'h2{font-family:"Instrument Serif",Georgia,serif;font-size:1.5rem;font-weight:700;color:var(--text);margin:2.5rem 0 1rem;padding-top:1.5rem;border-top:1px solid var(--border)}',
    'h3{font-family:"Inter",sans-serif;font-size:1.1rem;font-weight:600;color:var(--text);margin:1.5rem 0 .5rem}',
    'p,li{color:var(--muted);font-size:.95rem}',
    'a{color:var(--accent);text-decoration:none}a:hover{text-decoration:underline}',
    'ul{padding-left:1.25rem;margin:.5rem 0}',
    'code{background:var(--card);padding:.15rem .4rem;border-radius:4px;font-size:.85rem;color:var(--code);font-family:"JetBrains Mono",monospace}',
    'pre{background:var(--card);border:1px solid var(--border);border-radius:12px;padding:1.25rem;overflow-x:auto;margin:.75rem 0 1.25rem;font-size:.85rem;line-height:1.6}',
    'pre code{background:none;padding:0;color:var(--text)}',
    '.badge{display:inline-block;padding:.15rem .6rem;border-radius:9999px;font-size:.75rem;font-weight:600}',
    '.badge-post{background:#13b98120;color:var(--accent-light)}.badge-get{background:#22c55e20;color:#4ade80}',
    '.badge-required{background:#ef444420;color:#f87171}.badge-optional{background:var(--border);color:var(--muted)}',
    '.card{background:var(--card);border:1px solid var(--border);border-radius:12px;padding:1.25rem;margin:.75rem 0}',
    '.step{display:flex;gap:1rem;margin:.75rem 0}.step-num{min-width:2rem;height:2rem;border-radius:50%;background:var(--accent);color:#091a0f;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:.85rem}',
    '.param-table{width:100%;border-collapse:collapse;margin:.5rem 0}.param-table th{text-align:left;padding:.5rem;font-size:.8rem;color:var(--muted);border-bottom:1px solid var(--border)}.param-table td{padding:.5rem;font-size:.85rem;border-bottom:1px solid var(--border)}.param-table td:first-child{font-family:"JetBrains Mono",monospace;color:var(--code);white-space:nowrap}',
    '.hero-sub{color:var(--muted);font-size:1.1rem;margin-bottom:1.5rem}',
    '.nav-links{display:flex;gap:.75rem;flex-wrap:wrap;margin:1rem 0}',
    '.nav-links a{padding:.4rem .9rem;border-radius:8px;background:var(--card);border:1px solid var(--border);font-size:.85rem;transition:all .2s}.nav-links a:hover{border-color:var(--accent);text-decoration:none}',
    '.response-field{color:var(--accent-light)}',
    '</style></head><body><div class="wrap">',
    '<h1>SB0 Pay API</h1>',
    '<p class="hero-sub">Accept payments in your app with a few lines of code. Generate payment links, QR codes, and track transactions.</p>',
    '<div class="nav-links">',
    '<a href="#quickstart">Quick Start</a>',
    '<a href="#auth">Authentication</a>',
    '<a href="#create-payment">Create Payment</a>',
    '<a href="#get-payment">Get Payment</a>',
    '<a href="#list-payments">List Payments</a>',
    '<a href="#refund">Refund</a>',
    '<a href="#cancel">Cancel</a>',
    '<a href="#webhooks">Webhooks</a>',
    '<a href="#errors">Errors</a>',
    '<a href="#sdks">Code Examples</a>',
    '<a href="/v1/docs">Interactive Swagger Docs &rarr;</a>',
    '</div>',
    '<h2 id="quickstart">Quick Start</h2>',
    '<p>Get up and running in 3 steps:</p>',
    '<div class="step"><div class="step-num">1</div><div><strong>Get your API key</strong><br><span style="color:var(--muted)">Sign in to the <a href="https://sb0pay.web.app">SB0 Pay dashboard</a>, go to Settings &rarr; API Keys, and create a key with <code>payments:create</code> and <code>payments:read</code> permissions.</span></div></div>',
    '<div class="step"><div class="step-num">2</div><div><strong>Create a payment</strong><br><span style="color:var(--muted)">Send a POST request to <code>/api/v1/payments</code> with the amount. You get back a payment URL and QR code.</span></div></div>',
    '<div class="step"><div class="step-num">3</div><div><strong>Redirect or display QR</strong><br><span style="color:var(--muted)">Send your customer to the <code>paymentUrl</code> or display the <code>qrCodeDataUrl</code> for them to scan. Listen for webhooks or poll the status endpoint.</span></div></div>',
    '<div class="card"><strong>Base URL</strong><br><code>https://sb0pay-410118487888.us-central1.run.app/api/v1</code><br><br><strong>Local development</strong><br><code>http://localhost:3001/api/v1</code></div>',
    '<h2 id="auth">Authentication</h2>',
    '<p>All API requests require a Bearer token in the <code>Authorization</code> header:</p>',
    '<pre><code>Authorization: Bearer sb0_live_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</code></pre>',
    '<p>API keys are prefixed with <code>sb0_live_</code> (production) or <code>sb0_test_</code> (testing). Each key has scoped permissions:</p>',
    '<table class="param-table"><tr><th>Permission</th><th>Description</th></tr>',
    '<tr><td>payments:create</td><td>Create new payments</td></tr>',
    '<tr><td>payments:read</td><td>View payment details and list payments</td></tr>',
    '<tr><td>payments:update</td><td>Refund and cancel payments</td></tr>',
    '<tr><td>transactions:read</td><td>View transaction history</td></tr></table>',
    '<h2 id="create-payment">Create Payment</h2>',
    '<p><span class="badge badge-post">POST</span> <code>/api/v1/payments</code></p>',
    '<h3>Request Body</h3>',
    '<table class="param-table"><tr><th>Field</th><th>Type</th><th>Description</th></tr>',
    '<tr><td>amount</td><td>number <span class="badge badge-required">required</span></td><td>Amount in decimal format (e.g. <code>100.50</code>). NOT minor units.</td></tr>',
    '<tr><td>currency</td><td>string <span class="badge badge-optional">optional</span></td><td><code>ILS</code>, <code>USD</code>, <code>EUR</code>. Defaults to merchant currency.</td></tr>',
    '<tr><td>language</td><td>string <span class="badge badge-optional">optional</span></td><td>Payment page language: <code>he</code>, <code>en</code>, <code>ar</code>, <code>ru</code>, <code>auto</code></td></tr>',
    '<tr><td>description</td><td>string <span class="badge badge-optional">optional</span></td><td>Payment description (max 255 chars)</td></tr>',
    '<tr><td>lineItems</td><td>array <span class="badge badge-optional">optional</span></td><td>Each: <code>{ name, price, quantity, includesVat? }</code>. Sum must equal amount.</td></tr>',
    '<tr><td>customerEmail</td><td>string <span class="badge badge-optional">optional</span></td><td>Customer email</td></tr>',
    '<tr><td>customerName</td><td>string <span class="badge badge-optional">optional</span></td><td>Customer name</td></tr>',
    '<tr><td>customerPhone</td><td>string <span class="badge badge-optional">optional</span></td><td>Customer phone</td></tr>',
    '<tr><td>maxInstallments</td><td>number <span class="badge badge-optional">optional</span></td><td>Max installments (1-12)</td></tr>',
    '<tr><td>successUrl</td><td>string <span class="badge badge-optional">optional</span></td><td>Redirect after success</td></tr>',
    '<tr><td>cancelUrl</td><td>string <span class="badge badge-optional">optional</span></td><td>Redirect after cancel</td></tr>',
    '<tr><td>webhookUrl</td><td>string <span class="badge badge-optional">optional</span></td><td>URL for payment notifications</td></tr>',
    '<tr><td>metadata</td><td>object <span class="badge badge-optional">optional</span></td><td>Custom key-value data</td></tr></table>',
    '<h3>Example Request</h3>',
    '<pre><code>curl -X POST https://sb0pay-410118487888.us-central1.run.app/api/v1/payments \\\n  -H "Authorization: Bearer sb0_live_xxxxxxxx" \\\n  -H "Content-Type: application/json" \\\n  -d \'{ "amount": 250.00, "currency": "ILS", "description": "Order #12345",\n    "customerEmail": "customer@example.com",\n    "successUrl": "https://yoursite.com/success",\n    "webhookUrl": "https://yoursite.com/webhook",\n    "metadata": { "orderId": "12345" } }\'</code></pre>',
    '<h3>Response <code>201 Created</code></h3>',
    '<pre><code>{\n  <span class="response-field">"id"</span>: "a1b2c3d4-...",\n  <span class="response-field">"amount"</span>: 250.00,\n  <span class="response-field">"currency"</span>: "ILS",\n  <span class="response-field">"status"</span>: "pending",\n  <span class="response-field">"paymentUrl"</span>: "https://pay.allpay.co.il/...",\n  <span class="response-field">"qrCodeDataUrl"</span>: "data:image/png;base64,...",\n  <span class="response-field">"createdAt"</span>: "2025-05-04T10:30:00Z"\n}</code></pre>',
    '<h2 id="get-payment">Get Payment</h2>',
    '<p><span class="badge badge-get">GET</span> <code>/api/v1/payments/:id</code></p>',
    '<p>Retrieve details of a specific payment. Requires <code>payments:read</code>.</p>',
    '<pre><code>curl https://sb0pay-410118487888.us-central1.run.app/api/v1/payments/a1b2c3d4-... \\\n  -H "Authorization: Bearer sb0_live_xxxxxxxx"</code></pre>',
    '<h3>Response <code>200 OK</code></h3>',
    '<pre><code>{\n  "id": "a1b2c3d4-...", "amount": 250.00, "currency": "ILS",\n  "status": "completed", "description": "Order #12345",\n  "metadata": { "orderId": "12345" },\n  "createdAt": "2025-05-04T10:30:00Z", "updatedAt": "2025-05-04T10:35:00Z"\n}</code></pre>',
    '<h2 id="list-payments">List Payments</h2>',
    '<p><span class="badge badge-get">GET</span> <code>/api/v1/payments?limit=50&amp;offset=0</code></p>',
    '<table class="param-table"><tr><th>Query Param</th><th>Default</th><th>Description</th></tr>',
    '<tr><td>limit</td><td>50</td><td>Results per page (max 100)</td></tr>',
    '<tr><td>offset</td><td>0</td><td>Results to skip</td></tr></table>',
    '<h3>Response <code>200 OK</code></h3>',
    '<pre><code>{\n  "data": [ { "id": "...", "amount": 100, "status": "completed", ... } ],\n  "pagination": { "limit": 50, "offset": 0, "total": 142, "hasMore": true }\n}</code></pre>',
    '<h2 id="refund">Refund Payment</h2>',
    '<p><span class="badge badge-post">POST</span> <code>/api/v1/payments/:id/refund</code></p>',
    '<p>Refund a completed payment. Omit <code>amount</code> for full refund. Requires <code>payments:update</code>.</p>',
    '<pre><code>curl -X POST .../api/v1/payments/a1b2c3d4-.../refund \\\n  -H "Authorization: Bearer sb0_live_xxxxxxxx" \\\n  -H "Content-Type: application/json" \\\n  -d \'{ "amount": 50.00 }\'</code></pre>',
    '<h2 id="cancel">Cancel Payment</h2>',
    '<p><span class="badge badge-post">POST</span> <code>/api/v1/payments/:id/cancel</code></p>',
    '<p>Cancel a pending payment. Only works before completion. Requires <code>payments:update</code>.</p>',
    '<pre><code>curl -X POST .../api/v1/payments/a1b2c3d4-.../cancel \\\n  -H "Authorization: Bearer sb0_live_xxxxxxxx"</code></pre>',
    '<h2 id="webhooks">Webhooks</h2>',
    '<p>When a payment status changes, SB0 Pay POSTs to your <code>webhookUrl</code>:</p>',
    '<pre><code>{\n  "transactionId": "a1b2c3d4-...",\n  "status": "completed",\n  "amount": 250.00,\n  "currency": "ILS",\n  "timestamp": "2025-05-04T10:35:00Z"\n}</code></pre>',
    '<p>Return <code>200</code> to acknowledge. Use polling as a fallback.</p>',
    '<h3>Payment Statuses</h3>',
    '<table class="param-table"><tr><th>Status</th><th>Description</th></tr>',
    '<tr><td><code>pending</code></td><td>Waiting for customer</td></tr>',
    '<tr><td><code>completed</code></td><td>Payment successful</td></tr>',
    '<tr><td><code>failed</code></td><td>Payment failed</td></tr>',
    '<tr><td><code>cancelled</code></td><td>Cancelled by merchant</td></tr>',
    '<tr><td><code>refunded</code></td><td>Full refund processed</td></tr>',
    '<tr><td><code>partially_refunded</code></td><td>Partial refund processed</td></tr></table>',
    '<h2 id="errors">Error Handling</h2>',
    '<p>All errors follow a consistent format:</p>',
    '<pre><code>{\n  "error": {\n    "code": "INVALID_AMOUNT",\n    "message": "Amount must be a positive number",\n    "type": "invalid_request"\n  },\n  "timestamp": "2025-05-04T10:30:00Z",\n  "requestId": "uuid-..."\n}</code></pre>',
    '<table class="param-table"><tr><th>Type</th><th>Codes</th><th>Meaning</th></tr>',
    '<tr><td>authentication_error</td><td><code>MISSING_API_KEY</code>, <code>INVALID_API_KEY</code>, <code>INSUFFICIENT_PERMISSIONS</code></td><td>Check your API key</td></tr>',
    '<tr><td>invalid_request</td><td><code>INVALID_AMOUNT</code>, <code>INVALID_LINE_ITEMS</code>, <code>PAYMENT_NOT_FOUND</code></td><td>Check request body</td></tr>',
    '<tr><td>api_error</td><td><code>INTERNAL_ERROR</code>, <code>PAYMENT_PROVIDER_ERROR</code></td><td>Retry or contact support</td></tr></table>',
    '<h3>HTTP Status Codes</h3>',
    '<table class="param-table"><tr><th>Code</th><th>Meaning</th></tr>',
    '<tr><td>200</td><td>Success</td></tr><tr><td>201</td><td>Created</td></tr>',
    '<tr><td>400</td><td>Bad request</td></tr><tr><td>401</td><td>Unauthorized</td></tr>',
    '<tr><td>403</td><td>Forbidden</td></tr><tr><td>404</td><td>Not found</td></tr>',
    '<tr><td>502</td><td>Provider unavailable</td></tr><tr><td>500</td><td>Server error</td></tr></table>',
    '<h2 id="sdks">Code Examples</h2>',
    '<h3>JavaScript / Node.js</h3>',
    '<pre><code>const response = await fetch(\n  "https://sb0pay-410118487888.us-central1.run.app/api/v1/payments",\n  {\n    method: "POST",\n    headers: {\n      "Authorization": "Bearer sb0_live_xxxxxxxx",\n      "Content-Type": "application/json"\n    },\n    body: JSON.stringify({\n      amount: 100.50,\n      currency: "ILS",\n      description: "Order #12345",\n      customerEmail: "customer@example.com",\n      successUrl: "https://yoursite.com/success"\n    })\n  }\n);\nconst payment = await response.json();\nconsole.log(payment.paymentUrl); // redirect customer here</code></pre>',
    '<h3>Python</h3>',
    '<pre><code>import requests\n\nres = requests.post(\n    "https://sb0pay-410118487888.us-central1.run.app/api/v1/payments",\n    headers={\n        "Authorization": "Bearer sb0_live_xxxxxxxx",\n        "Content-Type": "application/json"\n    },\n    json={\n        "amount": 100.50,\n        "currency": "ILS",\n        "description": "Order #12345",\n        "customerEmail": "customer@example.com"\n    }\n)\npayment = res.json()\nprint(payment["paymentUrl"])</code></pre>',
    '<h3>PHP</h3>',
    '<pre><code>$ch = curl_init("https://sb0pay-410118487888.us-central1.run.app/api/v1/payments");\ncurl_setopt_array($ch, [\n    CURLOPT_POST =&gt; true,\n    CURLOPT_RETURNTRANSFER =&gt; true,\n    CURLOPT_HTTPHEADER =&gt; [\n        "Authorization: Bearer sb0_live_xxxxxxxx",\n        "Content-Type: application/json"\n    ],\n    CURLOPT_POSTFIELDS =&gt; json_encode([\n        "amount" =&gt; 100.50,\n        "currency" =&gt; "ILS",\n        "description" =&gt; "Order #12345"\n    ])\n]);\n$response = json_decode(curl_exec($ch), true);\necho $response["paymentUrl"];</code></pre>',
    '<h3>cURL</h3>',
    '<pre><code>curl -X POST https://sb0pay-410118487888.us-central1.run.app/api/v1/payments \\\n  -H "Authorization: Bearer sb0_live_xxxxxxxx" \\\n  -H "Content-Type: application/json" \\\n  -d \'{ "amount": 100.50, "currency": "ILS",\n    "description": "Order #12345",\n    "customerEmail": "customer@example.com" }\'</code></pre>',
    '<div style="margin-top:3rem;padding-top:1.5rem;border-top:1px solid var(--border);text-align:center">',
    '<p style="color:var(--muted);font-size:.85rem">SB0 Pay API v1.3.0 &middot; <a href="/v1/docs">Interactive Swagger Docs</a> &middot; <a href="/docs/openapi.json">OpenAPI Spec</a></p>',
    '<p style="color:var(--muted);font-size:.8rem;margin-top:.5rem">&copy; 2025 SB0 Pay</p>',
    '</div>',
    '</div></body></html>',
  ].join('\n');
}

export const docsLegacyController = new Elysia({ prefix: '/docs' })
  .get('/', ({ set }) => {
    set.headers['content-type'] = 'text/html; charset=utf-8';
    return buildDocsHtml();
  })
  .get('/openapi.json', () => ({
    openapi: '3.0.0',
    info: { title: 'SB0 Pay API', version: '1.2.0', description: 'Payment processing API. For full interactive docs visit /v1/docs' },
    servers: [{ url: '/api/v1', description: 'API' }],
    externalDocs: { description: 'Full Swagger UI', url: '/v1/docs' },
  }));
